require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DvdsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Dvd. As you add validations to Dvd, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
        title: 'Superbad',
        rating: 3,
        abstract_txt: "Superbad is a 2007 American comedy film directed by Greg Mottola and starring Jonah Hill and Michael Cera.",
        abstract_source: 'Wikipedia',
        abstract_url: 'https://en.wikipedia.org/wiki/Superbad_(film)',
        file_url: 'http://emachina/SUPERBAD_UNRATED.mp4',
        playback_time: 0
    }
  }

  let(:invalid_attributes) {
    {
        rating: 8,
        playback_time: 'middle'
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DvdsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all dvds as @dvds" do
      dvd = Dvd.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dvds)).to eq([dvd])
    end
  end

  describe "GET #show" do
    it "assigns the requested dvd as @dvd" do
      dvd = Dvd.create! valid_attributes
      get :show, {:id => dvd.to_param}, valid_session
      expect(assigns(:dvd)).to eq(dvd)
    end
  end

  describe "GET #new" do
    it "assigns a new dvd as @dvd" do
      get :new, {}, valid_session
      expect(assigns(:dvd)).to be_a_new(Dvd)
    end
  end

  describe "GET #edit" do
    it "assigns the requested dvd as @dvd" do
      dvd = Dvd.create! valid_attributes
      get :edit, {:id => dvd.to_param}, valid_session
      expect(assigns(:dvd)).to eq(dvd)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Dvd" do
        expect {
          post :create, {:dvd => valid_attributes}, valid_session
        }.to change(Dvd, :count).by(1)
      end

      it "assigns a newly created dvd as @dvd" do
        post :create, {:dvd => valid_attributes}, valid_session
        expect(assigns(:dvd)).to be_a(Dvd)
        expect(assigns(:dvd)).to be_persisted
      end

      it "redirects to the created dvd" do
        post :create, {:dvd => valid_attributes}, valid_session
        expect(response).to redirect_to(Dvd.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved dvd as @dvd" do
        post :create, {:dvd => invalid_attributes}, valid_session
        expect(assigns(:dvd)).to be_a_new(Dvd)
      end

      it "re-renders the 'new' template" do
        post :create, {:dvd => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { rating: 5 }
      }

      it "updates the requested dvd" do
        dvd = Dvd.create! valid_attributes
        put :update, {:id => dvd.to_param, :dvd => new_attributes}, valid_session
        dvd.reload
        expect(assigns(:dvd).rating).to eq(new_attributes[:rating])
      end

      it "assigns the requested dvd as @dvd" do
        dvd = Dvd.create! valid_attributes
        put :update, {:id => dvd.to_param, :dvd => valid_attributes}, valid_session
        expect(assigns(:dvd)).to eq(dvd)
      end

      it "redirects to the dvd" do
        dvd = Dvd.create! valid_attributes
        put :update, {:id => dvd.to_param, :dvd => valid_attributes}, valid_session
        expect(response).to redirect_to(dvd)
      end
    end

    context "with invalid params" do
      it "assigns the dvd as @dvd" do
        dvd = Dvd.create! valid_attributes
        put :update, {:id => dvd.to_param, :dvd => invalid_attributes}, valid_session
        expect(assigns(:dvd)).to eq(dvd)
      end

      it "re-renders the 'edit' template" do
        dvd = Dvd.create! valid_attributes
        put :update, {:id => dvd.to_param, :dvd => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested dvd" do
      dvd = Dvd.create! valid_attributes
      expect {
        delete :destroy, {:id => dvd.to_param}, valid_session
      }.to change(Dvd, :count).by(-1)
    end

    it "redirects to the dvds list" do
      dvd = Dvd.create! valid_attributes
      delete :destroy, {:id => dvd.to_param}, valid_session
      expect(response).to redirect_to(dvds_url)
    end
  end

end
